version: "3.5"

services:
  db:
    image: postgres:12.4-alpine
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      serv:
        aliases:
          - db      
    restart: always
networks:
  serv:
    name: serv
    driver: host    